### ISSUE TITLE
Verify gdalwarp can/cannot work across UTM zones

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/ca-naip#13]
Run a test on two qquads (right below lake Tahoe) on either side of the UTM 10 and 11 cutoff, and verify that gdalwarp can handle that or not.

**Comment by ghost** [comment]
@qjhart gdalbuildvrt itself cannot handle heterogeneous projections, so we need to revert back to building a vrt of each utm zone separately, then warping to the common 3310 projection, then combining.

**Comment by ghost** [comment]
Also, tried several tests. Received the error "Warning: gdalwarp -of VRT just takes into account the first source dataset. If all source datasets are in the same projection, try making a mosaic of them with gdalbuildvrt, and use the resulting VRT file as the input of gdalwarp -of VRT."  The problem is gdalbuildvrt will not take different projections. This is not going to work with a VRT output or using a gdalbuildvrt for the input source files.

**Comment by ghost** [comment]
Tried gdalwarp with a painful listing of tif files and with GTIFF as the default output format. "gdalwarp --config GDAL_CACHEMAX 500 -wm 50 -t_srs epsg:3310 -r cubic -tr 1 1 $d/m_3912063_sw_10_1_20140725.tif $d/m_3912064_ne_10_1_20140725.tif $d/m_3912064_nw_10_1_20140725.tif $d/m_3912064_se_10_1_20140712.tif $d/m_3912064_sw_10_1_20140712.tif $c/m_3911901_nw_11_1_20140808.tif $c/m_3911901_sw_11_1_20140723.tif $c/m_3911909_nw_11_1_20140723.tif LKTahoecmb_ca_albers.tif" While it did not give me any error messages and did create the output GeoTIFF, we really do not want to output GeoTIFFS. (I could use expansion instead).I have not checked the output file for accuracy. What seems clear is that the VRT format will not support more than one projection, which makes this difficult for our purposes, and I assume we do not want to create a huge GeoTIFF file as output.

**Comment by ghost** [comment]
One can do gdalbuildvrt of all tiffs in zone 10 and use gdalwarp that warp that to 3310 and similarly warp all utm zone 11 tiffs to 3310 then combine them into a common vrt file for further processing.
